<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProjectsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $projects = [
            [
                'name' => 'Afflispark',
                'slug' => Str::slug('Afflispark'),
                'category_id' => 2,
                'short_description' => 'Affiliate marketing platform with multi-tier vendor & affiliate commissions.',
                'long_description' => 'AffliSpark is a full-featured affiliate marketing platform where vendors can upload products and affiliates can promote them to earn commissions. The system supports multi-tier affiliate structures, allowing referrals to earn from standard affiliates, vendors, and super affiliates. Built with Laravel, it includes instant PayPal & Stripe split payouts, multi-language support, multi-currency handling, and advanced tracking for clicks, referrals, and product conversions.',
                'url' => 'https://affilspark.com/',
                'image' => 'assets/images/afflispark.png',
                'order' => 0,
                'is_featured' => true,
                'status' => 1,
                'features' => json_encode([
                    'Multi-vendor affiliate marketplace',
                    'Multi-tier affiliate referral system',
                    'Instant PayPal & Stripe split payouts',
                    'Click tracking, referral tracking & conversion analytics',
                    'Multi-language & multi-currency support',
                    'Vendor product upload & commission configuration',
                    'Affiliate dashboard with earning analytics',
                    'Super vendor & super affiliate commission hierarchy',
                ]),
                'technologies' => json_encode(['Laravel', 'MySQL', 'Bootstrap', 'jQuery', 'Stripe API', 'PayPal Payouts', 'REST API']),
                'skills_used' => json_encode([
                    'Payment gateway split payout integration',
                    'Advanced tracking system design',
                    'Multi-tier commission logic development',
                    'SaaS architecture & role-based access control',
                    'Multi-language and multi-currency implementation'
                ]),
            ],
            [
                'name' => 'Proxima Digital',
                'slug' => Str::slug('Proxima Digital'),
                'category_id' => 1,
                'short_description' => 'All-in-one IT solution platform built with Laravel, Vue.js, and TailwindCSS.',
                'long_description' => 'Proxima Digital is a comprehensive IT solutions platform designed for startups and enterprises. Built using Laravel and Vue.js, it offers seamless performance, real-time analytics, and a responsive interface powered by TailwindCSS. The platform streamlines service management, client interaction, and workflow automation for digital businesses.',
                'url' => 'https://proxima.mokaddes.com/',
                'image' => 'assets/images/proxima.png',
                'order' => 1,
                'is_featured' => true,
                'status' => 1,
                'features' => json_encode([
                    'Dynamic admin dashboard with role-based access',
                    'Project and client management system',
                    'Data visualization with charts and real-time updates',
                    'Integrated user authentication and notifications',
                    'API-ready architecture for mobile extension',
                ]),
                'technologies' => json_encode(['Laravel', 'Vue.js', 'TailwindCSS', 'MySQL', 'REST API', 'Pusher']),
                'skills_used' => json_encode(['Full-stack development', 'API design', 'Frontend integration', 'UX optimization']),
            ],
            [
                'name' => 'Vinitycard',
                'slug' => Str::slug('Vinitycard'),
                'category_id' => 5,
                'short_description' => 'Smart NFC business card platform for professionals and teams.',
                'long_description' => 'Vinitycard allows professionals to instantly share contact details using NFC or QR. The platform is built with Laravel and Livewire, providing analytics, contact sync, and custom design options for digital cards. It includes a clean admin dashboard for users to manage cards and track engagement.',
                'url' => 'https://vinitycard.com/',
                'image' => 'assets/images/vinitycard.png',
                'order' => 2,
                'is_featured' => true,
                'status' => 1,
                'features' => json_encode([
                    'Instant contact sharing via NFC/QR',
                    'Customizable digital card templates',
                    'Profile analytics and visitor tracking',
                    'Team management and bulk card generation',
                ]),
                'technologies' => json_encode(['Laravel', 'Livewire', 'Bootstrap', 'MySQL', 'JavaScript', 'NFC Integration']),
                'skills_used' => json_encode(['Laravel backend development', 'Livewire integration', 'UI development', 'Data analytics']),
            ],
            [
                'name' => 'MH ZONE',
                'slug' => Str::slug('MH ZONE'),
                'category_id' => 2,
                'short_description' => 'Multi-vendor eCommerce platform with dual buyer-seller mode.',
                'long_description' => 'MH ZONE is a next-generation eCommerce platform enabling users to operate as both buyer and seller. Built with Laravel and MySQL, it features inventory management, secure payment gateways, and vendor dashboards with analytics for smarter business decisions.',
                'url' => 'https://mhzone.mokaddes.com/',
                'image' => 'assets/images/mhzone.png',
                'order' => 3,
                'is_featured' => true,
                'status' => 1,
                'features' => json_encode([
                    'Dual user mode (Buyer/Seller)',
                    'Vendor store management system',
                    'Product inventory and order tracking',
                    'Integrated Stripe & PayPal payments',
                    'Sales analytics and reports dashboard',
                ]),
                'technologies' => json_encode(['Laravel', 'Bootstrap', 'MySQL', 'jQuery', 'Stripe API', 'PayPal SDK']),
                'skills_used' => json_encode(['Backend API development', 'Payment integration', 'Admin dashboard', 'Data visualization']),
            ],
            [
                'name' => 'Real Time Chat App',
                'slug' => Str::slug('Real Time Chat App'),
                'category_id' => 1,
                'short_description' => 'Instant messaging app built with Laravel, Vue.js & Pusher.',
                'long_description' => 'This real-time chat app allows users to communicate instantly via private and group chat rooms. Built with Laravel, Vue.js, and Pusher, it includes typing indicators, message read receipts, and notifications for a seamless communication experience.',
                'url' => 'https://chat.mokaddes.com/',
                'image' => 'assets/images/chat.png',
                'order' => 4,
                'is_featured' => false,
                'status' => 1,
                'features' => json_encode([
                    'Real-time messaging with chat rooms',
                    'Typing indicators & read receipts',
                    'Private and group chats',
                    'Pusher-based notifications',
                ]),
                'technologies' => json_encode(['Laravel', 'Vue.js', 'Pusher', 'TailwindCSS', 'MySQL']),
                'skills_used' => json_encode(['Real-time app development', 'Frontend integration', 'Backend architecture']),
            ],
            [
                'name' => 'BRP',
                'slug' => Str::slug('BRP'),
                'category_id' => 2,
                'short_description' => 'Automotive e-commerce for tuning, racing, and performance parts.',
                'long_description' => 'BRP is an e-commerce solution for motorsport enthusiasts and professional tuners. It offers a catalog for tuning, racing, drifting, and performance upgrades with inventory management, advanced filters, and smooth checkout features.',
                'url' => 'https://www.brp.online',
                'image' => 'assets/images/brp.gif',
                'order' => 5,
                'is_featured' => false,
                'status' => 1,
                'features' => json_encode([
                    'Advanced product catalog for motorsports',
                    'Inventory management and filtering',
                    'Secure checkout with multiple payment options',
                    'Responsive user interface for buyers',
                ]),
                'technologies' => json_encode(['Laravel', 'Bootstrap', 'MySQL', 'jQuery', 'Stripe API']),
                'skills_used' => json_encode(['Backend e-commerce setup', 'UI design', 'Payment integration']),
            ],
            [
                'name' => 'Franchises Available Now',
                'slug' => Str::slug('Franchises Available Now'),
                'category_id' => 3,
                'short_description' => 'Discover and evaluate franchise opportunities easily.',
                'long_description' => 'Franchises Available Now helps entrepreneurs explore franchise options filtered by investment, location, and category. Built with Laravel, it provides detailed insights, contact forms, and analytics for decision-making.',
                'url' => 'https://franchisesavailablenow.com/',
                'image' => 'assets/images/franchises.png',
                'order' => 6,
                'is_featured' => false,
                'status' => 1,
                'features' => json_encode([
                    'Search & filter franchises by interest and budget',
                    'Detailed franchise information',
                    'Contact and inquiry forms',
                    'Mobile-friendly interface',
                ]),
                'technologies' => json_encode(['Laravel', 'Bootstrap', 'MySQL', 'jQuery']),
                'skills_used' => json_encode(['Backend filtering', 'Frontend UX', 'Data management']),
            ],
            [
                'name' => 'Zentune',
                'slug' => Str::slug('Zentune'),
                'category_id' => 3,
                'short_description' => 'Vehicle tuning platform with Laravel REST API integration.',
                'long_description' => 'Zentune develops advanced tuning files for vehicles. Utilizing Laravel REST API, it ensures smooth app integration, real-time updates, and efficient file management for performance enhancement.',
                'url' => 'https://www.zentune.com',
                'image' => 'assets/images/zentune.png',
                'order' => 7,
                'is_featured' => false,
                'status' => 1,
                'features' => json_encode([
                    'Vehicle performance tuning files',
                    'REST API for app integration',
                    'Real-time updates and notifications',
                    'Stage and custom tuning options',
                ]),
                'technologies' => json_encode(['Laravel', 'REST API', 'MySQL', 'Vue.js']),
                'skills_used' => json_encode(['API development', 'Backend tuning logic', 'Integration with mobile apps']),
            ],
            [
                'name' => 'Everisamting',
                'slug' => Str::slug('Everisamting'),
                'category_id' => 3,
                'short_description' => 'Classified & event management platform with Laravel API.',
                'long_description' => 'Everisamting is a classifieds platform combining event management. Built with Laravel REST API, it supports posting, browsing, and event ticketing with mobile app integration.',
                'url' => 'https://everisamting.com/',
                'image' => 'assets/images/everisamting.png',
                'order' => 8,
                'is_featured' => false,
                'status' => 1,
                'features' => json_encode([
                    'Classified ads posting and browsing',
                    'Event listing and ticketing',
                    'REST API for mobile app',
                    'User-friendly dashboard',
                ]),
                'technologies' => json_encode(['Laravel', 'REST API', 'Bootstrap', 'MySQL']),
                'skills_used' => json_encode(['API integration', 'Backend development', 'UI enhancements']),
            ],
            [
                'name' => 'Service Provider',
                'slug' => Str::slug('Service Provider'),
                'category_id' => 5,
                'short_description' => 'Marketplace connecting users with service providers efficiently.',
                'long_description' => 'Service Provider platform enables users to find and book trusted service providers. Built with Laravel, it features service listings, reviews, booking management, and notifications for seamless user experience.',
                'url' => 'https://serviceprovider.ae/',
                'image' => 'assets/images/sp.png',
                'order' => 9,
                'is_featured' => false,
                'status' => 1,
                'features' => json_encode([
                    'Service discovery and booking',
                    'Provider reviews and ratings',
                    'Real-time notifications',
                    'User-friendly dashboard for service providers',
                ]),
                'technologies' => json_encode(['Laravel', 'Bootstrap', 'MySQL', 'jQuery']),
                'skills_used' => json_encode(['Backend API', 'Service management', 'UI/UX']),
            ],
            [
                'name' => 'Enjoy City Tour',
                'slug' => Str::slug('Enjoy City Tour'),
                'category_id' => 4,
                'short_description' => 'Tour booking platform for city adventures and sightseeing.',
                'long_description' => 'Enjoy City Tour allows users to explore and book exciting activities, guided tours, and city experiences. Built with Laravel and Bootstrap, it includes location-based search, booking management, and secure payments for travelers worldwide.',
                'url' => 'https://enjoycitytours.com/',
                'image' => 'assets/images/ect.png',
                'order' => 10,
                'is_featured' => false,
                'status' => 1,
                'features' => json_encode([
                    'Tour booking & itinerary management',
                    'Location-based search',
                    'Secure payment integration',
                    'Mobile-friendly interface',
                ]),
                'technologies' => json_encode(['Laravel', 'Bootstrap', 'MySQL', 'jQuery']),
                'skills_used' => json_encode(['Backend booking logic', 'Frontend UI', 'Payment integration']),
            ],
            [
                'name' => 'TCLI Library',
                'slug' => Str::slug('TCLI Library'),
                'category_id' => 4,
                'short_description' => 'Online library with clubs, forums, and API integration.',
                'long_description' => 'TCLI Library is an advanced online library system with integrated clubs, forums, and REST API support. Users can access books, discuss topics, and connect through digital communities.',
                'url' => 'https://www.tclibrary.com',
                'image' => 'assets/images/tcli.png',
                'order' => 11,
                'is_featured' => false,
                'status' => 1,
                'features' => json_encode([
                    'Digital book collection',
                    'Community clubs and discussion forums',
                    'REST API for mobile integration',
                    'User-friendly interface',
                ]),
                'technologies' => json_encode(['Laravel', 'REST API', 'Bootstrap', 'MySQL']),
                'skills_used' => json_encode(['API development', 'Frontend integration', 'Community management']),
            ],
            [
                'name' => 'Dhereye Delivery',
                'slug' => Str::slug('Dhereye Delivery'),
                'category_id' => 5,
                'short_description' => 'Courier and logistics platform with live tracking.',
                'long_description' => 'Dhereye Delivery is a logistics platform for corporate and retail customers. Built with Laravel, it features delivery scheduling, product tracking, and notifications for efficient delivery management.',
                'url' => 'https://enjoycitytours.com/',
                'image' => 'assets/images/dhereye.png',
                'order' => 12,
                'is_featured' => false,
                'status' => 0,
                'features' => json_encode([
                    'Courier scheduling and tracking',
                    'Order management dashboard',
                    'Customer notifications',
                    'Admin panel for delivery monitoring',
                ]),
                'technologies' => json_encode(['Laravel', 'Bootstrap', 'MySQL', 'jQuery']),
                'skills_used' => json_encode(['Backend logistics logic', 'Tracking system', 'Dashboard UI']),
            ],
        ];

        DB::table('projects')->insert($projects);
    }
}
