<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProjectsTableSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            $this->project([
                'name' => 'Afflispark',
                'category_id' => 2,
                'short_description' => 'Affiliate marketing platform with multi-tier vendor & affiliate commissions.',
                'long_description' => 'AffliSpark is a full-featured affiliate marketing platform where vendors can upload products and affiliates can promote them to earn commissions. The system supports multi-tier affiliate structures, allowing referrals to earn from standard affiliates, vendors, and super affiliates. Built with Laravel, it includes instant PayPal & Stripe split payouts, multi-language support, multi-currency handling, and advanced tracking for clicks, referrals, and product conversions.',
                'problem' => 'The client needed a scalable affiliate marketplace where vendors, affiliates, and super affiliates could operate under a single platform with automated commission payouts and real-time tracking — without manual spreadsheet reconciliation.',
                'solution' => 'I designed a multi-tier commission engine with role-based dashboards, automated split payouts via PayPal and Stripe, and a tracking system that captures clicks, referrals, and conversions at every level of the hierarchy.',
                'my_contribution' => 'I architected the backend commission engine, referral tracking logic, payout integration, dashboard analytics, and full release pipeline.',
                'url' => 'https://affilspark.com/',
                'image' => 'assets/images/afflispark.png',
                'order' => 0,
                'is_featured' => true,
                'features' => [
                    'Multi-vendor affiliate marketplace',
                    'Multi-tier affiliate referral system',
                    'Instant PayPal & Stripe split payouts',
                    'Click tracking, referral tracking & conversion analytics',
                    'Multi-language & multi-currency support',
                    'Vendor product upload & commission configuration',
                    'Affiliate dashboard with earning analytics',
                    'Super vendor & super affiliate commission hierarchy',
                ],
                'technologies' => ['Laravel', 'MySQL', 'Bootstrap', 'jQuery', 'Stripe API', 'PayPal Payouts', 'REST API'],
                'skills_used' => [
                    'Payment gateway split payout integration',
                    'Advanced tracking system design',
                    'Multi-tier commission logic development',
                    'SaaS architecture & role-based access control',
                    'Multi-language and multi-currency implementation',
                ],
                'screenshots' => [
                    'assets/images/afflispark.png',
                    'assets/images/gallery/project/Screenshot_1.jpg',
                ],
            ]),
            $this->project([
                'name' => 'Proxima Digital',
                'category_id' => 1,
                'short_description' => 'All-in-one IT solution platform built with Laravel, Vue.js, and TailwindCSS.',
                'long_description' => 'Proxima Digital is a comprehensive IT solutions platform designed for startups and enterprises. Built using Laravel and Vue.js, it offers seamless performance, real-time analytics, and a responsive interface powered by TailwindCSS. The platform streamlines service management, client interaction, and workflow automation for digital businesses.',
                'problem' => 'The client needed a unified system to manage services, client projects, and internal operations instead of juggling multiple disconnected tools.',
                'solution' => 'I built a modular Laravel + Vue.js application with structured management screens, real-time reporting, and reusable component architecture.',
                'my_contribution' => 'I delivered the full-stack implementation, dashboard logic, API-ready structure, and responsive frontend.',
                'url' => 'https://proxima.mokaddes.com/',
                'image' => 'assets/images/proxima.png',
                'order' => 1,
                'is_featured' => true,
                'features' => [
                    'Dynamic admin dashboard with role-based access',
                    'Project and client management system',
                    'Data visualization with charts and real-time updates',
                    'Integrated user authentication and notifications',
                    'API-ready architecture for mobile extension',
                ],
                'technologies' => ['Laravel', 'Vue.js', 'TailwindCSS', 'MySQL', 'REST API', 'Pusher'],
                'skills_used' => [
                    'Full-stack development',
                    'API design',
                    'Frontend integration',
                    'UX optimization',
                ],
                'screenshots' => [
                    'assets/images/proxima.png',
                    'assets/images/gallery/project/proxima_1.jpg',
                ],
            ]),
            $this->project([
                'name' => 'Vinitycard',
                'category_id' => 5,
                'short_description' => 'Smart NFC business card platform for professionals and teams.',
                'long_description' => 'Vinitycard allows professionals to instantly share contact details using NFC or QR. The platform is built with Laravel and Livewire, providing analytics, contact sync, and custom design options for digital cards. It includes a clean admin dashboard for users to manage cards and track engagement.',
                'problem' => 'Professionals needed a modern way to share contact information and track engagement without relying on printed business cards.',
                'solution' => 'I created a digital card platform with NFC and QR sharing, real-time analytics, and a user-friendly dashboard for card management.',
                'my_contribution' => 'I delivered the Laravel backend, Livewire interactive components, analytics dashboard, and contact-sharing workflow.',
                'url' => 'https://vinitycard.com/',
                'image' => 'assets/images/vinitycard.png',
                'order' => 2,
                'is_featured' => true,
                'features' => [
                    'Instant contact sharing via NFC/QR',
                    'Customizable digital card templates',
                    'Profile analytics and visitor tracking',
                    'Team management and bulk card generation',
                ],
                'technologies' => ['Laravel', 'Livewire', 'Bootstrap', 'MySQL', 'JavaScript', 'NFC Integration'],
                'skills_used' => [
                    'Laravel backend development',
                    'Livewire integration',
                    'UI development',
                    'Data analytics',
                ],
                'screenshots' => [
                    'assets/images/vinitycard.png',
                    'assets/images/gallery/project/vinitycard_1.jpg',
                    'assets/images/gallery/project/vinitycard_2.jpg',
                ],
            ]),
            $this->project([
                'name' => 'MH ZONE',
                'category_id' => 2,
                'short_description' => 'Multi-vendor eCommerce platform with dual buyer-seller mode.',
                'long_description' => 'MH ZONE is a next-generation eCommerce platform enabling users to operate as both buyer and seller. Built with Laravel and MySQL, it features inventory management, secure payment gateways, and vendor dashboards with analytics for smarter business decisions.',
                'problem' => 'The client wanted a marketplace where users could seamlessly switch between buying and selling from a single account while keeping orders and inventory organized.',
                'solution' => 'I developed dual-role authentication flows, vendor store management, inventory tracking, and integrated payment processing.',
                'my_contribution' => 'I handled backend business rules, vendor dashboard flows, payment gateway setup, and admin analytics views.',
                'url' => 'https://mhzone.mokaddes.com/',
                'image' => 'assets/images/mhzone.png',
                'order' => 3,
                'is_featured' => true,
                'features' => [
                    'Dual user mode (Buyer/Seller)',
                    'Vendor store management system',
                    'Product inventory and order tracking',
                    'Integrated Stripe & PayPal payments',
                    'Sales analytics and reports dashboard',
                ],
                'technologies' => ['Laravel', 'Bootstrap', 'MySQL', 'jQuery', 'Stripe API', 'PayPal SDK'],
                'skills_used' => [
                    'Backend API development',
                    'Payment integration',
                    'Admin dashboard',
                    'Data visualization',
                ],
                'screenshots' => [
                    'assets/images/mhzone.png',
                ],
            ]),
            $this->project([
                'name' => 'Real Time Chat App',
                'category_id' => 1,
                'short_description' => 'Instant messaging app built with Laravel, Vue.js & Pusher.',
                'long_description' => 'This real-time chat app allows users to communicate instantly via private and group chat rooms. Built with Laravel, Vue.js, and Pusher, it includes typing indicators, message read receipts, and notifications for a seamless communication experience.',
                'problem' => 'Users needed instant, real-time communication without page refreshes or delayed message delivery.',
                'solution' => 'I built a real-time messaging system with Pusher event broadcasting, conversation rooms, and responsive UI states.',
                'my_contribution' => 'I implemented the real-time messaging flow, Vue.js frontend reactivity, notification handling, and backend channel architecture.',
                'url' => 'https://chat.mokaddes.com/',
                'image' => 'assets/images/chat.png',
                'order' => 4,
                'features' => [
                    'Real-time messaging with chat rooms',
                    'Typing indicators & read receipts',
                    'Private and group chats',
                    'Pusher-based notifications',
                ],
                'technologies' => ['Laravel', 'Vue.js', 'Pusher', 'TailwindCSS', 'MySQL'],
                'skills_used' => [
                    'Real-time app development',
                    'Frontend integration',
                    'Backend architecture',
                ],
                'screenshots' => [
                    'assets/images/chat.png',
                    'assets/images/gallery/project/chat_1.jpg',
                    'assets/images/gallery/project/chat_2.jpg',
                ],
            ]),
            $this->project([
                'name' => 'BRP',
                'category_id' => 2,
                'short_description' => 'Automotive e-commerce for tuning, racing, and performance parts.',
                'long_description' => 'BRP is an e-commerce solution for motorsport enthusiasts and professional tuners. It offers a catalog for tuning, racing, drifting, and performance upgrades with inventory management, advanced filters, and smooth checkout features.',
                'problem' => 'The business needed a specialized product catalog for automotive performance parts with a streamlined browsing and checkout experience.',
                'solution' => 'I created a focused commerce layout with product catalog controls, category-based filtering, and a simplified checkout flow.',
                'my_contribution' => 'I handled backend e-commerce structure, UI implementation, and payment gateway integration.',
                'url' => 'https://www.brp.online',
                'image' => 'assets/images/brp.gif',
                'order' => 5,
                'features' => [
                    'Advanced product catalog for motorsports',
                    'Inventory management and filtering',
                    'Secure checkout with multiple payment options',
                    'Responsive user interface for buyers',
                ],
                'technologies' => ['Laravel', 'Bootstrap', 'MySQL', 'jQuery', 'Stripe API'],
                'skills_used' => [
                    'Backend e-commerce setup',
                    'UI design',
                    'Payment integration',
                ],
                'screenshots' => [
                    'assets/images/brp.gif',
                ],
            ]),
            $this->project([
                'name' => 'Franchises Available Now',
                'category_id' => 3,
                'short_description' => 'Discover and evaluate franchise opportunities easily.',
                'long_description' => 'Franchises Available Now helps entrepreneurs explore franchise options filtered by investment, location, and category. Built with Laravel, it provides detailed insights, contact forms, and analytics for decision-making.',
                'problem' => 'Potential franchise buyers needed a centralized platform to browse, filter, and compare opportunities without scattered information.',
                'solution' => 'I built a searchable franchise directory with structured detail pages, inquiry management, and comparison-ready filters.',
                'my_contribution' => 'I implemented filtering logic, page architecture, and frontend usability enhancements.',
                'url' => 'https://franchisesavailablenow.com/',
                'image' => 'assets/images/franchises.png',
                'order' => 6,
                'features' => [
                    'Search & filter franchises by interest and budget',
                    'Detailed franchise information',
                    'Contact and inquiry forms',
                    'Mobile-friendly interface',
                ],
                'technologies' => ['Laravel', 'Bootstrap', 'MySQL', 'jQuery'],
                'skills_used' => [
                    'Backend filtering',
                    'Frontend UX',
                    'Data management',
                ],
                'screenshots' => [
                    'assets/images/franchises.png',
                    'assets/images/gallery/project/franchises-available-now_1.jpg',
                    'assets/images/gallery/project/franchises-available-now_2.jpg',
                ],
            ]),
            $this->project([
                'name' => 'Zentune',
                'category_id' => 3,
                'short_description' => 'ECU remapping & vehicle tuning portal with AI support agent and credit-based file delivery.',
                'long_description' => 'Zentune is a purpose-built ECU remapping and tuning file portal serving workshops and tuners across Australia. Users upload OBD, bench, or boot reads and either download instant, dyno-validated files from a curated library or submit a brief for a custom, vehicle-specific calibration. Built with Laravel and Bootstrap, the platform combines a credit-based purchase system, Stripe payments, and an Intercom-powered AI support agent that handles tuning file questions and ticketing around the clock.',
                'problem' => 'The client needed a fast, reliable way for workshops to get tuning files without manual back-and-forth, plus a support channel that could handle high volumes of technical questions without overwhelming the team.',
                'solution' => 'I led development of the full portal, including instant and custom file request flows, a prepaid credit system for purchases, Stripe-based payment handling, and integrated an Intercom AI agent to automate first-line support and ticket triage.',
                'my_contribution' => 'As team leader I owned the full website build end-to-end and implemented the Intercom AI agent integration for automated customer support.',
                'url' => 'https://www.zentune.com',
                'image' => 'assets/images/zentune.png',
                'order' => 7,
                'is_featured' => true,
                'features' => [
                    'Instant & custom ECU tuning file requests',
                    'Credit-based purchase and payment system',
                    'Stripe payment integration',
                    'Intercom AI agent for automated support & ticketing',
                    'Dealer program with volume pricing and white-label options',
                    'Order history and 24/7 file re-download access',
                ],
                'technologies' => ['Laravel', 'Bootstrap', 'jQuery', 'AJAX', 'MySQL', 'Stripe API', 'Intercom AI Agent'],
                'skills_used' => [
                    'Team leadership & full project delivery',
                    'Payment gateway integration',
                    'AI-powered support agent integration',
                    'Credit/wallet system design',
                ],
                'screenshots' => [
                    'assets/images/zentune.png',
                ],
            ]),
            $this->project([
                'name' => 'Everisamting',
                'category_id' => 3,
                'short_description' => 'Classified & event management platform with Laravel API.',
                'long_description' => 'Everisamting is a classifieds platform combining event management. Built with Laravel REST API, it supports posting, browsing, and event ticketing with mobile app integration.',
                'problem' => 'The team needed a single platform to manage classified listings and event workflows instead of maintaining separate systems.',
                'solution' => 'I built a Laravel backend with listing management, event ticketing, and API-first architecture for mobile clients.',
                'my_contribution' => 'I delivered the API integration layer, backend development, and interface improvements.',
                'url' => 'https://everisamting.com/',
                'image' => 'assets/images/everisamting.png',
                'order' => 8,
                'features' => [
                    'Classified ads posting and browsing',
                    'Event listing and ticketing',
                    'REST API for mobile app',
                    'User-friendly dashboard',
                ],
                'technologies' => ['Laravel', 'REST API', 'Bootstrap', 'MySQL'],
                'skills_used' => [
                    'API integration',
                    'Backend development',
                    'UI enhancements',
                ],
                'screenshots' => [
                    'assets/images/everisamting.png',
                ],
            ]),
            $this->project([
                'name' => 'Service Provider',
                'category_id' => 5,
                'short_description' => 'Marketplace connecting users with service providers efficiently.',
                'long_description' => 'Service Provider platform enables users to find and book trusted service providers. Built with Laravel, it features service listings, reviews, booking management, and notifications for seamless user experience.',
                'problem' => 'The business needed a trusted marketplace with provider profiles, customer reviews, and booking flows consolidated in one platform.',
                'solution' => 'I designed a searchable service directory with booking workflows, review management, and automated notification triggers.',
                'my_contribution' => 'I implemented backend booking logic, service management flows, and frontend UI support.',
                'url' => 'https://serviceprovider.ae/',
                'image' => 'assets/images/sp.png',
                'order' => 9,
                'features' => [
                    'Service discovery and booking',
                    'Provider reviews and ratings',
                    'Real-time notifications',
                    'User-friendly dashboard for service providers',
                ],
                'technologies' => ['Laravel', 'Bootstrap', 'MySQL', 'jQuery'],
                'skills_used' => [
                    'Backend API',
                    'Service management',
                    'UI/UX',
                ],
                'screenshots' => [
                    'assets/images/sp.png',
                ],
            ]),
            $this->project([
                'name' => 'Enjoy City Tour',
                'category_id' => 4,
                'short_description' => 'Transfer & city tour booking platform with Google sign-in and a mobile app REST API.',
                'long_description' => 'Enjoy City Tour is a transfer service and city tour booking platform serving travelers across Rome and Italy, offering standard transfers, luxury transfers, and curated city tour packages. Built with Laravel, Bootstrap, and jQuery, the platform includes Google social sign-in for fast checkout and a REST API layer that powers a companion mobile app.',
                'problem' => 'Travelers needed a simple way to browse and book airport, port, and city transfers alongside tour packages, while the business also needed a mobile app to reach customers on the go.',
                'solution' => 'As part of the team, I helped build the complete booking flow — from tour/transfer selection through checkout — and developed the REST API that the mobile app consumes for bookings and account access.',
                'my_contribution' => 'I worked on the booking flow implementation and built the REST API used by the mobile app.',
                'url' => 'https://enjoycitytours.com/',
                'image' => 'assets/images/ect.png',
                'order' => 10,
                'features' => [
                    'Standard, luxury & city tour package booking',
                    'Google sign-in for quick checkout',
                    'REST API for companion mobile app',
                    'Airport, port & city pickup/drop-off scheduling',
                    'FAQ & booking policy pages',
                ],
                'technologies' => ['Laravel', 'Bootstrap', 'jQuery', 'AJAX', 'Google OAuth', 'REST API', 'MySQL'],
                'skills_used' => [
                    'Booking flow development',
                    'REST API development for mobile',
                    'OAuth/social login integration',
                ],
                'screenshots' => [
                    'assets/images/ect.png',
                ],
            ]),
            $this->project([
                'name' => 'TCLI Library',
                'category_id' => 4,
                'short_description' => 'Online library with clubs, forums, and API integration.',
                'long_description' => 'TCLI Library is an advanced online library system with integrated clubs, forums, and REST API support. Users can access books, discuss topics, and connect through digital communities.',
                'problem' => 'The client needed a digital library platform that also supported community features like clubs, forums, and mobile access.',
                'solution' => 'I created a content-driven library platform with community features, discussion forums, and API-ready data structures.',
                'my_contribution' => 'I contributed API development, frontend integration, and community workflow design.',
                'url' => 'https://www.tclibrary.com',
                'image' => 'assets/images/tcli.png',
                'order' => 11,
                'features' => [
                    'Digital book collection',
                    'Community clubs and discussion forums',
                    'REST API for mobile integration',
                    'User-friendly interface',
                ],
                'technologies' => ['Laravel', 'REST API', 'Bootstrap', 'MySQL'],
                'skills_used' => [
                    'API development',
                    'Frontend integration',
                    'Community management',
                ],
                'screenshots' => [
                    'assets/images/tcli.png',
                ],
            ]),
            $this->project([
                'name' => 'Dhereye Delivery',
                'category_id' => 5,
                'short_description' => 'Courier and logistics platform with live tracking.',
                'long_description' => 'Dhereye Delivery is a logistics platform for corporate and retail customers. Built with Laravel, it features delivery scheduling, product tracking, and notifications for efficient delivery management.',
                'problem' => 'Delivery operations needed a centralized system to manage orders, track shipments in real time, and keep customers informed throughout the process.',
                'solution' => 'I built a logistics workflow with delivery scheduling, live tracking, automated status updates, and customer notification triggers.',
                'my_contribution' => 'I worked on backend logistics logic, real-time tracking features, and operational dashboard interfaces.',
                'url' => 'https://dhereye.com/',
                'image' => 'assets/images/dhereye.png',
                'order' => 12,
                'is_featured' => false,
                'status' => 0,
                'features' => [
                    'Courier scheduling and tracking',
                    'Order management dashboard',
                    'Customer notifications',
                    'Admin panel for delivery monitoring',
                ],
                'technologies' => ['Laravel', 'Bootstrap', 'MySQL', 'jQuery'],
                'skills_used' => [
                    'Backend logistics logic',
                    'Tracking system',
                    'Dashboard UI',
                ],
                'screenshots' => [
                    'assets/images/dhereye.png',
                ],
            ]),
            $this->project([
                'name' => 'OmniYou',
                'category_id' => 4,
                'short_description' => 'All-in-one client management platform unifying portals, billing, and team collaboration.',
                'long_description' => 'OmniYou replaces multiple disconnected software subscriptions by unifying client portals, document handling, shared task spaces, communication logs, and billing triggers under one intelligent platform. It serves creative agencies, healthcare providers, freelance professionals, consulting firms, and education centers with a multi-tenant architecture, custom file manager, and an API assistant for KPI reporting.',
                'problem' => 'Service-based businesses were juggling separate tools for client portals, document tracking, task management, and billing, with no single source of truth for client relationships.',
                'solution' => 'I planned, designed, and built a multi-tenant Laravel platform with a unified client workspace, custom file manager, real-time collaboration with access controls, centralized transaction/document trails, and an API-driven KPI report generator.',
                'my_contribution' => 'I worked as team leader, handling planning, design, and most of the development single-handedly, with some data entry and testing support from the team.',
                'url' => 'https://www.mauditready.com/',
                'image' => 'assets/images/omniyou.jpg',
                'order' => 13,
                'is_featured' => true,
                'features' => [
                    'Multi-tenant client portal & workspace',
                    'Custom file manager for document handling',
                    'Shared task spaces & communication logs',
                    'Centralized billing triggers & transaction trails',
                    'API assistant for KPI report generation',
                    'Role-based real-time collaboration',
                ],
                'technologies' => ['Laravel', 'Bootstrap', 'jQuery', 'AJAX', 'MySQL', 'REST API'],
                'skills_used' => [
                    'Multi-tenancy architecture',
                    'Team leadership & solo full-stack delivery',
                    'API design & KPI reporting',
                    'Document/file management systems',
                ],
                'screenshots' => [
                    'assets/images/omniyou.png',
                ],
            ]),
            $this->project([
                'name' => 'Kokonte',
                'category_id' => 3,
                'short_description' => "Ghana's free online classifieds marketplace for goods and services.",
                'long_description' => "Kokonte.com is Ghana's leading free classifieds platform, connecting buyers and sellers of vehicles, real estate, jobs, electronics, furniture, and local services. The platform offers 100% free listings, a wide range of categories, and nationwide reach across cities including Accra, Kumasi, Takoradi, and Tamale.",
                'problem' => 'Ghanaian buyers and sellers needed a fast, free, and trustworthy classifieds marketplace instead of fee-based or scattered listing channels.',
                'solution' => "I contributed to the admin panel and REST API layer that power listing management, categorization, and moderation across the platform's marketplace categories.",
                'my_contribution' => 'As a team member, I worked on the admin panel and REST API.',
                'url' => 'https://kokonte.com/',
                'image' => 'assets/images/kokonte.png',
                'order' => 14,
                'features' => [
                    'Free classified ad listings',
                    'Multi-category marketplace (vehicles, property, jobs, electronics & more)',
                    'Location-based browsing across Ghana',
                    'Admin moderation panel',
                    'REST API backend',
                ],
                'technologies' => ['Laravel', 'Bootstrap', 'jQuery', 'AJAX', 'MySQL', 'REST API'],
                'skills_used' => [
                    'Admin panel development',
                    'REST API development',
                ],
                'screenshots' => [
                    'assets/images/kokonte.png',
                ],
            ]),
            $this->project([
                'name' => 'AllNet France',
                'category_id' => 5,
                'short_description' => 'Corporate platform maintenance for a telecom, networking & IoT distributor.',
                'long_description' => 'AllNet France is the French arm of the Allnet Group, a value-added distributor of telecommunications, networking, and IoT solutions with over three decades of industry history. I worked on their existing Laravel platform, resolving functional and design issues and implementing catalog features to support their product distribution business.',
                'problem' => 'The existing platform had outstanding bugs, design inconsistencies, and needed an infinite category loop plus reliable product import/export for the distributor catalog.',
                'solution' => 'I resolved the reported issues and design problems, implemented an infinite category loop for catalog navigation, and built product import/export functionality.',
                'my_contribution' => 'I handled this as a single-developer project, working directly on the existing Laravel codebase.',
                'url' => 'https://allnetfrance.fr',
                'image' => 'assets/images/allnet.png',
                'order' => 15,
                'features' => [
                    'Infinite category navigation loop',
                    'Product catalog import/export',
                    'Bug fixes on existing platform',
                    'Design/UI issue resolution',
                ],
                'technologies' => ['Laravel', 'MySQL', 'Bootstrap'],
                'skills_used' => [
                    'Legacy codebase maintenance',
                    'Catalog import/export logic',
                    'Bug fixing & UI polish',
                ],
                'screenshots' => [
                    'assets/images/allnetfrance.png',
                ],
            ]),
            $this->project([
                'name' => 'Physics Phenoms',
                'category_id' => 6,
                'short_description' => 'Bangladeshi EdTech platform helping SSC & HSC students master Physics.',
                'long_description' => 'Physics Phenoms is a Bangladeshi online education platform focused on making Physics accessible and enjoyable for SSC, HSC, and admission-test students. It combines Facebook-based live classes, detailed notes, and personal mentorship, and has already helped thousands of students build confidence in the subject.',
                'problem' => 'Students preparing for SSC/HSC and admission exams needed structured, mentorship-backed Physics learning support built quickly and affordably.',
                'solution' => 'I built the platform as a solo, AI-assisted ("vibe coding") project using Laravel and TailwindCSS, moving from concept to a working platform rapidly with Claude as a development partner.',
                'my_contribution' => 'I independently designed and developed the full platform.',
                'url' => 'https://pp.sikhun.com/',
                'image' => 'assets/images/pp.png',
                'order' => 16,
                'features' => [
                    'Facebook-based live class integration',
                    'Structured notes and study resources',
                    'Personal mentorship support',
                    'Bangla-language student-facing platform',
                ],
                'technologies' => ['Laravel', 'TailwindCSS', 'MySQL'],
                'skills_used' => [
                    'Solo full-stack development',
                    'AI-assisted ("vibe coding") development workflow',
                    'EdTech platform design',
                ],
                'screenshots' => [
                    'assets/images/physicsphenoms.png',
                ],
            ]),
            $this->project([
                'name' => 'International Forex Awards',
                'category_id' => 7,
                'short_description' => 'Custom WordPress plugin powering nomination, voting, and award management for a global forex industry awards platform.',
                'long_description' => 'International Forex Awards is a global recognition platform for forex brokers, fintech innovators, trading platforms, and financial institutions, connecting the industry through nomination, public voting, and sponsorship events across B2B and B2C award categories. I developed a custom WordPress plugin that powers the entire awards mechanism end-to-end: nominee submission, public voting, category-wise winner calculation, and a dedicated admin management dashboard, replacing what would otherwise require multiple disconnected plugins or a separate application.',
                'problem' => 'The client needed a structured, tamper-resistant nomination and voting system spanning dozens of B2B and B2C award categories, with public-facing forms and vote counts embeddable directly into WordPress pages, plus an admin interface to manage nominees, categories, voting periods, and results.',
                'solution' => 'I built a custom WordPress plugin from the ground up, covering nominee registration forms, a public voting system with duplicate-vote safeguards, category-wise winner determination logic, and an admin panel for managing awards, categories, nominees, and multiple concurrent award cycles. Front-end forms and voting widgets were implemented as WordPress shortcodes so the client\'s Elementor-based marketing pages could embed them anywhere without custom page templates.',
                'my_contribution' => 'I independently designed and developed the full custom plugin, including the database schema, admin management screens, and all front-end shortcodes for nomination and voting.',
                'url' => 'https://internationalfxawards.com/home/',
                'image' => 'assets/images/internationalfxawards.png',
                'order' => 17,
                'is_featured' => true,
                'features' => [
                    'Custom nominee submission forms via shortcode',
                    'Public voting system with duplicate-vote protection',
                    'Category-wise winner calculation across B2B & B2C awards',
                    'Support for multiple concurrent award events',
                    'Admin dashboard for managing nominees, categories & votes',
                    'Sponsorship and event page shortcodes',
                ],
                'technologies' => ['WordPress', 'PHP', 'MySQL', 'jQuery', 'AJAX', 'Elementor'],
                'skills_used' => [
                    'Custom WordPress plugin development',
                    'Shortcode & widget development',
                    'Voting system architecture',
                    'Admin panel development',
                ],
                'screenshots' => [
                    'assets/images/internationalfxawards.webp',
                ],
            ]),
            $this->project([
                'name' => 'Basic Automation',
                'category_id' => 8,
                'short_description' => 'Open-source n8n workflow collection for AI-powered Facebook & WhatsApp automation.',
                'long_description' => 'Basic Automation is a self-initiated, open-source collection of three n8n workflows demonstrating end-to-end AI-driven social media and messaging automation using self-hosted, local LLMs via Ollama. It covers scheduled Facebook content posting, an AI Messenger chatbot, and an AI WhatsApp chatbot, each with conversation memory and Graph API integration.',
                'problem' => 'Small businesses and Facebook Page owners often need consistent posting and responsive messaging support without paid AI API costs or manual effort, and without depending on third-party SaaS automation tools.',
                'solution' => 'I built three reusable n8n workflows: a scheduled Facebook auto-poster that pulls topics from Google Sheets and generates on-brand post copy with a local Ollama model, and two AI chatbots (Messenger & WhatsApp) that verify webhook subscriptions, maintain per-sender conversation memory, and reply through the Meta Graph API — all powered by self-hosted Ollama models instead of paid AI APIs.',
                'my_contribution' => 'I independently designed, built, and open-sourced all three n8n workflows end-to-end.',
                'url' => 'https://github.com/mokaddes/basic-automation.git',
                'image' => 'assets/images/basic-automation.png',
                'order' => 18,
                'features' => [
                    'Scheduled Facebook auto-posting from a Google Sheets content queue',
                    'Random topic selection with AI-generated post copy (150-200 words, emojis, hashtags)',
                    'AI Messenger chatbot with webhook verification & conversation memory',
                    'AI WhatsApp chatbot with webhook verification & conversation memory',
                    'Self-hosted Ollama models (gemma3:4b, deepseek-coder-v2) — no paid AI API required',
                    'Optional Google Docs logging of conversations',
                ],
                'technologies' => ['n8n', 'Ollama', 'Facebook Graph API', 'WhatsApp Graph API', 'Google Sheets API', 'Google Docs API', 'Webhooks'],
                'skills_used' => [
                    'n8n workflow automation',
                    'Local LLM integration (Ollama)',
                    'Webhook & Meta Graph API integration',
                    'Conversation memory design for chatbots',
                    'Open-source project delivery',
                ],
                'screenshots' => [
                    'assets/images/n8n.png',
                ],
            ]),
        ];

        DB::table('projects')->insert($projects);
    }

    private function project(array $project): array
    {
        return [
            'name' => $project['name'],
            'slug' => Str::slug($project['name']),
            'category_id' => $project['category_id'],
            'short_description' => $project['short_description'],
            'long_description' => $project['long_description'],
            'problem' => $project['problem'],
            'solution' => $project['solution'],
            'my_contribution' => $project['my_contribution'],
            'url' => $project['url'] ?? null,
            'image' => $project['image'] ?? null,
            'order' => $project['order'] ?? 0,
            'is_featured' => $project['is_featured'] ?? false,
            'status' => $project['status'] ?? 1,
            'features' => json_encode($project['features'] ?? []),
            'technologies' => json_encode($project['technologies'] ?? []),
            'skills_used' => json_encode($project['skills_used'] ?? []),
            'screenshots' => json_encode($project['screenshots'] ?? []),
        ];
    }
}
